### ISSUE TITLE
Is there any pretrained model for the encoder-dual-decoder (EDD)?

### ISSUE THREAD

**Issue by phamquiluan** [ibm-aur-nlp/PubTabNet#2]
paper link: https://arxiv.org/pdf/1911.10683.pdf

**Comment by zhxgj** [comment]
> paper link: https://arxiv.org/pdf/1911.10683.pdf

Yes, there is. It is under IBM open sourcing approval.

**Comment by curiousily** [comment]
Hey @zhxgj,

Do you have any news on the approval progress? Can you open-source the code for the model?

Thanks for providing the dataset!

**Comment by zhxgj** [comment]
> Hey @zhxgj,
> 
> Do you have any news on the approval progress? Can you open-source the code for the model?
> 
> Thanks for providing the dataset!

Hi @curiousily ,

Thanks for your interests. There is a pre-trained model and we are under legal review for open-sourcing the code. Due to IP issues, it may take a long time to open-source the code. We will keep following up with our IP lawyers on this case.

**Comment by CristianAragon** [comment]
@zhxgj  
Great work!

Waiting open source too !

**Comment by weinixuehao** [comment]
The model using this dataset can to inference scanned image in which contains chinese table?

**Comment by zcunyi** [comment]
> > paper link: https://arxiv.org/pdf/1911.10683.pdf
> 
> Yes, there is. It is under IBM open sourcing approval.

Hi， where is the pre-trained model ?
when  you open-source the code for the model?

**Comment by vanche** [comment]
Any updates?

**Comment by vhiwase** [comment]
> > paper link: https://arxiv.org/pdf/1911.10683.pdf
> 
> Yes, there is. It is under IBM open sourcing approval.

@zhxgj any updates?

**Comment by ajjimeno** [comment]
@vhiwase, there are no updates yet to make the model publicly available.

**Comment by phamquiluan** [comment]
Đã 3 năm trôi qua, không biết team đã bị layoff chưa, chứ mình là mình đổi field nghiên cứu cmnr =))
