### ISSUE TITLE
Jupyter Notebooks?

### ISSUE THREAD

**Issue by felipeboffnunes** [ibm-aur-nlp/PubTabNet#7]
I think you may have taken out the notebooks because of IP? 
I'm working on my masters and this dataset will help me a lot (like, A LOT, thanks a bunch for creating it...), I wanted to give it a look on the jupyter notebooks.

**Comment by felipeboffnunes** [comment]
Sorry for not looking around more. The notebooks are at IBM.
https://dataplatform.cloud.ibm.com/analytics/notebooks/v2/0aa641b0-af25-4470-b9e1-6b33d6b5b66a/view?access_token=b7d5880bb60c253457a72e3ec76f9ab40ccc42c607331acdcbbbe21be4c46bc8

Would be interesting to link them there!
Sorry to bother!

**Comment by zhxgj** [comment]
@felipeboffnunes thanks. The notebook is also available here: https://github.com/ibm-aur-nlp/PubTabNet/blob/master/exploring_PubTabNet_dataset.ipynb
